#
# cltool.R (version 2.3.1)
# Various functions for K-means cluster analysis
#

#Name: k.means
#Conduct a k-means clustering with the first "n.cluster" subjects as the initial cluster centers
#Example: k.means(data,n.cluster=3)

k.means <- function(data,n.cluster){
	kmeans(data,centers=data[1:n.cluster,],iter.max=20)
}

# Name: snake.ch
# Produces a snake chart for a k-means cluster analysis
# Example: snake.ch(kmoutput)

snake.ch <- function(km,scale=FALSE){
x <- 1:(dim(km$centers)[2])
y <- km$centers

if(scale)y<-scale(y)

matplot(x,t(y),type="b",xaxt="n",xlab="Variables",ylab="Scores")
axis(side=1,at=x,labels=as.character(x))
}

# Name: cluster.mean
# Produces average value of numeric data by each cluster generated by kmeans or k.means
# Example: cluster.mean(data, kmoutput)

cluster.mean <- function(data, km, na.rm=FALSE){
        mean.fn <- function(x,nr=na.rm) mean(x,na.rm=nr)

        n.f <- sapply(data, is.numeric)
	sp <- split(data[,n.f], km$cluster)
	t(sapply(sp,function(x){sapply(x,mean.fn)}))

}

# Name: cluster.sd
#  Produces s.d. of numeric data by each cluster generated by kmeans or k.means
# Example: cluster.sd(data, kmoutput)

cluster.sd <- function(data, km){
	n.f <- sapply(data, is.numeric)
	sp <- split(data[,n.f], km$cluster)
	t(sapply(sp,function(x){sapply(x,sd)}))
}

# Name: cluster.table
# Produces tables of categorical data by each cluster generated by kmeans or k.means
# Example: ct <- cluster.table(data, kmoutput)
#          ct[1,1] 

cluster.table <- function(data, km){
	c.f <- sapply(data, is.factor)
	sp <- split(data[,c.f], km$cluster)
	t(sapply(sp,function(x){sapply(x,table)}))
}

# Name: cluster.plot
# Draw a scatteplot of observations with each cluster distinguished by
# different colors
# Example: cluster.plot(data, kmoutput, dim=c(1,2))

cluster.plot <- function(data, km, dim=1:2){
  library(ggplot2)
  library(plotly)
  library(GGally)
  
  if(!is.character(km$cluster)) cl <- as.character(km$cluster)
  else cl <- km$cluster
  
  g <- ggpairs(data, columns=dim, aes(colour=cl))
  ggplotly(g)
}

# Name: snake.ch2
# Produces a snake chart for a k-means cluster analysis (ggplot version)
# Example: snake.ch2(km_result)
snake.ch2 <- function(km_result) {
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  
  centers_df <- as.data.frame(km_result$centers)
  centers_df$cluster <- factor(rownames(centers_df))
  
  # Save the original variable order
  var_order <- colnames(km_result$centers)
  
  # Convert centers to long format
  centers_long <- centers_df %>%
    pivot_longer(-cluster, names_to = "Variable", values_to = "Mean") %>%
    mutate(Variable = factor(Variable, levels = var_order))
  
  # Plot
  ggplot(centers_long, aes(x = Variable, y = Mean, group = cluster, color = cluster)) +
    geom_line(size = 1) +
    geom_point(size = 2) +
    theme_minimal() +
    labs(title = "Snake Chart of Cluster Profiles",
         x = "Variables",
         y = "Cluster Center Value") +
    coord_flip() +
    facet_wrap(~cluster)
}